apiVersion: v2
name: azure-industrial-iot
version: 0.4.5-rc
description: Azure Industrial IoT allows plant operators to discover OPC UA enabled servers in a factory network and register them in Azure IoT Hub.
type: application
keywords:
- azure
- iot
- iiot
- industrial-iot
- azure-industrial-iot
- opc-ua
home: https://github.com/Azure/Industrial-IoT
maintainers:
- name: Karapet Kostandyan
  email: kakostan@microsoft.com
icon: https://raw.githubusercontent.com/Azure/Industrial-IoT/main/docs/media/microsoft-symbol.png
appVersion: 2.8.4
