{{- if .Values.deployment.microServices.jobs.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "azure-industrial-iot.jobs.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    app.kubernetes.io/name: {{ template "azure-industrial-iot.name" . }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
    app.kubernetes.io/component: opc-jobs
    app.kubernetes.io/part-of: azure-industrial-iot
{{- if .Values.deployment.microServices.jobs.extraLabels }}
{{ toYaml .Values.deployment.microServices.jobs.extraLabels | indent 4 }}
{{- end }}
{{- if .Values.deployment.microServices.jobs.deploymentAnnotations }}
  annotations:
{{ toYaml .Values.deployment.microServices.jobs.deploymentAnnotations | indent 4 }}
{{- end }}
spec:
  replicas: {{ .Values.deployment.microServices.jobs.replicas }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ template "azure-industrial-iot.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
      app.kubernetes.io/component: opc-jobs
      app.kubernetes.io/part-of: azure-industrial-iot
  template:
    metadata:
      labels:
        helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
        app.kubernetes.io/name: {{ template "azure-industrial-iot.name" . }}
        app.kubernetes.io/managed-by: {{ .Release.Service }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        app.kubernetes.io/version: {{ .Chart.AppVersion }}
        app.kubernetes.io/component: opc-jobs
        app.kubernetes.io/part-of: azure-industrial-iot
{{- if .Values.deployment.microServices.jobs.extraLabels }}
{{ toYaml .Values.deployment.microServices.jobs.extraLabels | indent 8 }}
{{- end }}
      annotations:
        # Required to detect deployment change when 10_industrial_iot_env_secret.yaml is changed.
        checksum/config: {{ include (print $.Template.BasePath "/10_industrial_iot_env_secret.yaml") . | sha256sum }}
{{- if .Values.deployment.microServices.jobs.podAnnotations }}
{{ toYaml .Values.deployment.microServices.jobs.podAnnotations | indent 8 }}
{{- end }}
    spec:
      serviceAccountName: {{ template "azure-industrial-iot.serviceAccountName" . }}
{{- if .Values.image.pullSecrets }}
      imagePullSecrets:
{{ toYaml .Values.image.pullSecrets | indent 6 }}
{{- end }}
      containers:
      - name: jobs-service-container
        image: {{ .Values.image.registry }}/{{ .Values.deployment.microServices.jobs.imageRepository }}:{{ .Values.image.tag }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        {{- if .Values.deployment.microServices.jobs.extraArgs }}
        args:
          {{- range .Values.deployment.microServices.jobs.extraArgs }}
          - {{ . }}
          {{- end }}
        {{- end }}
{{- if .Values.deployment.microServices.jobs.resources }}
        resources:
{{ toYaml .Values.deployment.microServices.jobs.resources | indent 10 }}
{{- end }}
        env:
        - name: PCS_KEYVAULT_URL
          valueFrom:
            secretKeyRef:
              name: {{ template "azure-industrial-iot.env.fullname" . }}
              key: PCS_KEYVAULT_URL
        - name: PCS_IOTHUB_CONNSTRING
          valueFrom:
            secretKeyRef:
              name: {{ template "azure-industrial-iot.env.fullname" . }}
              key: PCS_IOTHUB_CONNSTRING
        - name: PCS_SERVICEBUS_CONNSTRING
          valueFrom:
            secretKeyRef:
              name: {{ template "azure-industrial-iot.env.fullname" . }}
              key: PCS_SERVICEBUS_CONNSTRING
        - name: PCS_APPINSIGHTS_NAME
          valueFrom:
            secretKeyRef:
              name: {{ template "azure-industrial-iot.env.fullname" . }}
              key: PCS_APPINSIGHTS_NAME
        - name: PCS_APPINSIGHTS_INSTRUMENTATIONKEY
          valueFrom:
            secretKeyRef:
              name: {{ template "azure-industrial-iot.env.fullname" . }}
              key: PCS_APPINSIGHTS_INSTRUMENTATIONKEY
{{- if .Values.deployment.microServices.jobs.extraEnv }}
{{ toYaml .Values.deployment.microServices.jobs.extraEnv | indent 8 }}
{{- end }}
{{- end }}
