{{- if .Values.deployment.microServices.publisher.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "azure-industrial-iot.publisher.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    app.kubernetes.io/name: {{ template "azure-industrial-iot.name" . }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
    app.kubernetes.io/component: opc-publisher-service
    app.kubernetes.io/part-of: azure-industrial-iot
{{- if .Values.deployment.microServices.publisher.extraLabels }}
{{ toYaml .Values.deployment.microServices.publisher.extraLabels | indent 4 }}
{{- end }}
{{- if .Values.deployment.microServices.publisher.deploymentAnnotations }}
  annotations:
{{ toYaml .Values.deployment.microServices.publisher.deploymentAnnotations | indent 4 }}
{{- end }}
spec:
  replicas: {{ .Values.deployment.microServices.publisher.replicas }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ template "azure-industrial-iot.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
      app.kubernetes.io/component: opc-publisher-service
      app.kubernetes.io/part-of: azure-industrial-iot
  template:
    metadata:
      labels:
        helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
        app.kubernetes.io/name: {{ template "azure-industrial-iot.name" . }}
        app.kubernetes.io/managed-by: {{ .Release.Service }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        app.kubernetes.io/version: {{ .Chart.AppVersion }}
        app.kubernetes.io/component: opc-publisher-service
        app.kubernetes.io/part-of: azure-industrial-iot
{{- if .Values.deployment.microServices.publisher.extraLabels }}
{{ toYaml .Values.deployment.microServices.publisher.extraLabels | indent 8 }}
{{- end }}
      annotations:
        # Required to detect deployment change when 10_industrial_iot_env_secret.yaml is changed.
        checksum/config: {{ include (print $.Template.BasePath "/10_industrial_iot_env_secret.yaml") . | sha256sum }}
{{- if .Values.deployment.microServices.publisher.podAnnotations }}
{{ toYaml .Values.deployment.microServices.publisher.podAnnotations | indent 8 }}
{{- end }}
    spec:
      serviceAccountName: {{ template "azure-industrial-iot.serviceAccountName" . }}
{{- if .Values.image.pullSecrets }}
      imagePullSecrets:
{{ toYaml .Values.image.pullSecrets | indent 6 }}
{{- end }}
      containers:
      - name: opc-publisher-service-container
        image: {{ .Values.image.registry }}/{{ .Values.deployment.microServices.publisher.imageRepository }}:{{ .Values.image.tag }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        {{- if .Values.deployment.microServices.publisher.extraArgs }}
        args:
          {{- range .Values.deployment.microServices.publisher.extraArgs }}
          - {{ . }}
          {{- end }}
        {{- end }}
{{- if .Values.deployment.microServices.publisher.resources }}
        resources:
{{ toYaml .Values.deployment.microServices.publisher.resources | indent 10 }}
{{- end }}
        ports:
        - containerPort: 9045
        env:
{{- /* env  section will be populated by environment variables specified in env.txt file */}}
{{- $envSecretName := include "azure-industrial-iot.env.fullname" . }}
{{- range .Files.Lines "env.txt" }}
{{- $keyName := trim . }}
{{- if $keyName }}
        - name: {{ $keyName }}
          valueFrom:
            secretKeyRef:
              name: {{ $envSecretName }}
              key: {{ $keyName }}
{{- end }}
{{- end }}
{{- if .Values.deployment.microServices.publisher.extraEnv }}
{{ toYaml .Values.deployment.microServices.publisher.extraEnv | indent 8 }}
{{- end }}
{{- end }}
