{{- if .Values.deployment.microServices.frontend.enabled }}
{{- if ( ne .Values.azure.auth.required true ) }}
{{- fail "frontend requires authentication to be enabled" }}
{{- end }}
apiVersion: v1
kind: Service
metadata:
  name: {{ template "azure-industrial-iot.frontend.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    app.kubernetes.io/name: {{ template "azure-industrial-iot.name" . }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
    app.kubernetes.io/component: {{ template "azure-industrial-iot.frontend.component" . }}
    app.kubernetes.io/part-of: azure-industrial-iot
{{- if .Values.deployment.microServices.frontend.extraLabels }}
{{ toYaml .Values.deployment.microServices.frontend.extraLabels | indent 4 }}
{{- end }}
{{- if .Values.deployment.microServices.frontend.service.annotations }}
  annotations:
{{ toYaml .Values.deployment.microServices.frontend.service.annotations | indent 4 }}
{{- end }}
spec:
  type: {{ .Values.deployment.microServices.frontend.service.type }}
  selector:
    app.kubernetes.io/name: {{ template "azure-industrial-iot.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: {{ template "azure-industrial-iot.frontend.component" . }}
    app.kubernetes.io/part-of: azure-industrial-iot
{{- if .Values.deployment.microServices.frontend.service.clusterIP }}
  clusterIP: {{ .Values.deployment.microServices.frontend.service.clusterIP }}
{{- end }}
{{- if .Values.deployment.microServices.frontend.service.externalIPs }}
  externalIPs:
{{ toYaml .Values.deployment.microServices.frontend.service.externalIPs | indent 2 }}
{{- end }}
{{- if .Values.deployment.microServices.frontend.service.loadBalancerIP }}
  loadBalancerIP: {{ .Values.deployment.microServices.frontend.service.loadBalancerIP }}
{{- end }}
{{- if .Values.deployment.microServices.frontend.service.loadBalancerSourceRanges }}
  loadBalancerSourceRanges:
{{ toYaml .Values.deployment.microServices.frontend.service.loadBalancerSourceRanges | indent 2 }}
{{- end }}
  ports:
  - port: {{ .Values.deployment.microServices.frontend.service.httpPort }}
    targetPort: 80
    protocol: TCP
    name: http
{{- if .Values.deployment.microServices.frontend.service.httpNodePort }}
    nodePort: {{ .Values.deployment.microServices.frontend.service.httpNodePort }}
{{- end }}
  - port: {{ .Values.deployment.microServices.frontend.service.httpsPort }}
    targetPort: 443
    protocol: TCP
    name: https
{{- if .Values.deployment.microServices.frontend.service.httpsNodePort }}
    nodePort: {{ .Values.deployment.microServices.frontend.service.httpsNodePort }}
{{- end }}
{{- end }}
